### ISSUE TITLE
Multiple image tags not respected

### ISSUE THREAD

**Issue by mwfister** [uptick/gitops#31]
Low priority due to how infrequently this would occur, but when multiple tags are assoicated with the same image, gitops currently selects the first image tag. This caused a bumped `eh` image to lose its `eh` tag

![image](https://user-images.githubusercontent.com/19923506/99924687-5ab02a80-2d8f-11eb-8871-e6d244ccc033.png)

**Comment by jarekwg** [comment]
Fixed in 0c93664f8978d58f4179f770aedfeb2e3ece15c6
