### ISSUE TITLE
Run deployments in parallel

### ISSUE THREAD

**Issue by furious-luke** [uptick/gitops#6]
The Helm deployments have always been carried out in serial to minimise the risk of catastrophe. However the code is stable enough now to run in parallel. Let's change the system to run each Helm command in parallel.

This should be easy enough using asyncio; we should be able to launch a sequence of background tasks on a thread executor.

**Comment by Sticky-Bits** [comment]
Can leverage the async run commands from the client tool in feature/async-gitops. Perhaps move them to a utils file.

**Comment by jarekwg** [comment]
It's fast enough w Helm3 that this is no longer a concern.
